# name: Deploy to Vercel

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4

#       - name: Install Vercel CLI
#         run: npm install --global vercel@latest

#       - name: Pull Vercel Environment
#         env:
#           VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
#           VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
#         run: |
#           vercel pull --yes \
#             --token=${{ secrets.VERCEL_TOKEN }} \
#             --scope=${{ secrets.VERCEL_ORG_ID }}

#       - name: Build Project
#         run: |
#           vercel build \
#             --token=${{ secrets.VERCEL_TOKEN }} \
#             --scope=${{ secrets.VERCEL_ORG_ID }}

#       - name: Deploy to Production
#         run: |
#           vercel deploy --prebuilt --prod \
#             --token=${{ secrets.VERCEL_TOKEN }} \
#             --scope=${{ secrets.VERCEL_ORG_ID }}
#